# Sets the theme to Cayman
theme: jekyll-theme-cayman
# Sets the title
title: CatOS Website
# Sets the description
description: The official CatOS website
# Sets the GitHub repo
github:
  repo: catos-scratch/catos
